# Definition of Domesday disks
# 'Offset' aligns frame numbers
# 'UID' is checked by cintcode to determine correct laserdisk
path = '../domesday-data/'
defaultDisk = 'natA'
Disks = {
  'natA':{
    'Offset': -83,
    'UID': 'U1=986\r',
    'adlFile': '%snatA.adl' % path,
    'frameForm': '%snatA-frames/frame%%05i.jpg' % path,
    'mp4File': '%snatA.mp4' % path,
    'mp4Offset': -84
    },
  'comN': {
    'Offset':-26,
    'UID': 'U1=067\r',
    'adlFile': '%scomN.adl' % path,
    'frameForm': '%scomN-frames/frame%%05i.jpg' % path,
    'mp4File': '%scmN.mp4' % path,
    'mp4Offset': -27
    }, 
  'comS':{
    'Offset': -31,
    'UID': 'U1=066\r',
    'adlFile': '%scomS.adl' % path,
    'frameForm': '%scomS-frames/frame%%05i.jpg' % path,
    'mp4File': '%scomS.mp4' % path,
    'mp4Offset': -32
    }
  }
# size of screen
DispX = 800
DispY = 640
#
# mode = 0 for execution by 6502 emulation only
# mode = 1 for execution by 6502, shadowed by cintcode
# mode = 2 for execution by cintcode, with fallback to 6502 for unhandled LF$ instructions
# mode = 3 for execution by cintcode emulation only
mode = 3
# mode may not be changed if modeLock is True
modeLock = True
# maxticks is maximum number of cintcodes executed per frame (25 per sec)
# It can be reduced to provided a slower - BBC-like - 'experience' 
maxticks = 10000
# When operating in mode 1, 'misMatch' is the limit of discrepancies between 6502 and cintcode 
# before program exits.
misMatch = 10
# Can be set during running to trace cintcode and 6502 execution
callTracing = False
cintTracing = False
mpuTracing  = False
# Trace and print filenames will be generated by the program
traceFile = None
printFile = None
# If opencv-python is installed, frames will be generated on-the-fly from
# .mp4 files.  Otherwise, directories of .jpg stills are used.
useCV2 = True
# Place holders for runtime global variables
adlFile = None
mp4File = None
adlDirectory = {}
FCresponse = b'A2\r'
#
# ==========================  END of CONFIGURATION =============================


